Repository contiki-ng/contiki-ng, pull requests merged in 2018-11, with the labels that each got.

#746 Native border router: clearer error messages
  os/services/rpl-border-router/native/slip-dev.c
  os/services/rpl-border-router/native/tun-bridge.c
Labels: pr/include-in-v4.2

#754 Change help messages to specify the -v argument as non-optional
  os/services/rpl-border-router/native/slip-config.c
  tools/serial-io/tunslip6.c
Labels: pr/bugfix

#773 Build system: enable compiling with arch directory at arbitrary paths
  Makefile.include
  arch/cpu/arm/cortex-m/Makefile.cortex-m
  arch/cpu/arm/cortex-m/cm3/Makefile.cm3
  arch/cpu/arm/cortex-m/cm4/Makefile.cm4
  arch/cpu/cc2538/Makefile.cc2538
  arch/cpu/cc26x0-cc13x0/Makefile.cc26x0-cc13x0
  arch/cpu/msp430/Makefile.msp430
  arch/cpu/nrf52832/Makefile.nrf52832
  arch/cpu/simplelink-cc13xx-cc26xx/cc13x0-cc26x0/Makefile.cc13x0-cc26x0
  arch/cpu/simplelink-cc13xx-cc26xx/cc13x2-cc26x2/Makefile.cc13x2-cc26x2
  arch/platform/cc2538dk/Makefile.cc2538dk
  arch/platform/cc26x0-cc13x0/Makefile.cc26x0-cc13x0
  arch/platform/cooja/Makefile.cooja
  arch/platform/native/Makefile.native
  arch/platform/nrf52dk/Makefile.nrf52dk
  arch/platform/openmote-cc2538/Makefile.openmote-cc2538
  arch/platform/simplelink/cc13xx-cc26xx/Makefile.cc13xx-cc26xx
  arch/platform/sky/Makefile.common
  arch/platform/sky/Makefile.sky
  arch/platform/zoul/Makefile.zoul
Labels: pr/enhancement
