Repository contiki-ng/contiki-ng, pull requests merged in 2018-02, with the labels that each got.

#294 Correctly check against minumum RX frame length
  arch/cpu/cc26xx-cc13xx/rf-core/ieee-mode.c
Labels: pr/bugfix

#295 Allow Shell operaction for CC13xx/CC26xx
  arch/platform/srf06-cc26xx/platform.c
Labels: pr/bugfix

#300 Fix project name
  LICENSE.md
Labels: documentation

#307 TSCH schedule printout
  examples/6tisch/simple-node/Makefile
  os/net/mac/tsch/tsch-schedule.c
  os/sys/log.h
Labels: pr/enhancement

#317 Use the GPIO HAL for Zoul sensor drivers
  arch/platform/zoul/dev/ac-dimmer.c
  arch/platform/zoul/dev/grove-gyro.c
  arch/platform/zoul/dev/motion-sensor.c
  arch/platform/zoul/dev/tsl256x.c
  arch/platform/zoul/dev/weather-meter.c
Labels: pr/enhancement

#320 Update README wording and add shields
  README.md
Labels: documentation

#318 Tidy-up MODULES
  Makefile.include
  arch/platform/cc2538dk/Makefile.cc2538dk
  arch/platform/cooja/Makefile.cooja
  arch/platform/jn516x/Makefile.jn516x
  arch/platform/native/Makefile.native
  arch/platform/nrf52dk/Makefile.nrf52dk
  arch/platform/openmote-cc2538/Makefile.openmote-cc2538
  arch/platform/sky/Makefile.sky
  arch/platform/srf06-cc26xx/Makefile.srf06-cc26xx
  arch/platform/zoul/Makefile.zoul
Labels: pr/enhancement

#326 Fix build under GNU make v3.81
  Makefile.include
Labels: bug/critical, pr/bugfix

#329 Add missing extern keyword
  os/net/mac/tsch/tsch-private.h
Labels: bug/low, pr/bugfix
