Repository contiki-ng/contiki-ng, pull requests merged in 2018-09, with the labels that each got.

#580 Use LOG_ constants infavour of PRINTF for rpl-classic
  os/net/routing/rpl-classic/rpl-dag-root.c
  os/net/routing/rpl-classic/rpl-dag.c
  os/net/routing/rpl-classic/rpl-ext-header.c
  os/net/routing/rpl-classic/rpl-icmp6.c
  os/net/routing/rpl-classic/rpl-mrhof.c
  os/net/routing/rpl-classic/rpl-nbr-policy.c
  os/net/routing/rpl-classic/rpl-of0.c
  os/net/routing/rpl-classic/rpl-timers.c
  os/net/routing/rpl-classic/rpl.c
Labels: pr/enhancement

#646 Fix RPL classic compilation for TARGET sky
  os/net/routing/rpl-classic/rpl-dag-root.c
Labels: bug, bug/medium, pr/bugfix

#578 Nightly testbed runs
  examples/benchmarks/rpl-req-resp/Makefile
  examples/benchmarks/rpl-req-resp/node.c
  examples/benchmarks/rpl-req-resp/parse.py
  examples/benchmarks/rpl-req-resp/project-conf.h
  examples/benchmarks/rpl-req-resp/sim.csc
  examples/benchmarks/testbeds/cooja8.c
  examples/benchmarks/testbeds/sics-firefly.c
  tests/03-compile-arm-ports-02/Makefile
Labels: pr/enhancement

#645 Add qualifier const to ip addresses in uip-ds6-route methods
  os/net/ipv6/tcpip.c
  os/net/ipv6/uip-ds6-route.c
  os/net/ipv6/uip-ds6-route.h
  tests/15-rpl-classic/code/receiver-node.c
Labels: pr/enhancement

#647 Fix multicast engine stats extension usage
  os/net/ipv6/multicast/esmrf.c
  os/net/ipv6/multicast/esmrf.h
  os/net/ipv6/multicast/smrf.h
Labels: bug, bug/medium, pr/bugfix

#651 add '\0' terminal character
  examples/rpl-border-router/webserver/httpd-simple.c
  tools/serial-io/tunslip6.c
Labels: pr/bugfix

#622 Simplify configuration of the CC13xx/CC26xx ROM bootloader
  arch/cpu/cc26xx-cc13xx/cc13xx-cc26xx-conf.h
  arch/cpu/cc26xx-cc13xx/ccxxware-conf.h
  arch/platform/srf06-cc26xx/launchpad/cc1310/board.h
  arch/platform/srf06-cc26xx/launchpad/cc1350/board.h
  arch/platform/srf06-cc26xx/launchpad/cc2640r2/board.h
  arch/platform/srf06-cc26xx/launchpad/cc2650/board.h
  arch/platform/srf06-cc26xx/sensortag/cc1350/board.h
  arch/platform/srf06-cc26xx/sensortag/cc2650/board.h
  arch/platform/srf06-cc26xx/srf06/cc13xx/board.h
  arch/platform/srf06-cc26xx/srf06/cc26xx/board.h
  examples/platform-specific/cc26xx/cc26xx-web-demo/project-conf.h
  examples/platform-specific/cc26xx/project-conf.h
  examples/platform-specific/cc26xx/very-sleepy-demo/project-conf.h
  examples/sensniff/srf06-cc26xx/target-conf.h
Labels: pr/enhancement

#637 TSCH stats and adaptive TSCH channel selection
  arch/platform/cooja/dev/cooja-radio.c
  examples/6tisch/channel-selection-demo/Makefile
  examples/6tisch/channel-selection-demo/README.md
  examples/6tisch/channel-selection-demo/node.c
  examples/6tisch/channel-selection-demo/project-conf.h
  examples/6tisch/tsch-stats/Makefile
  examples/6tisch/tsch-stats/README.md
  examples/6tisch/tsch-stats/node.c
  examples/6tisch/tsch-stats/project-conf.h
  os/contiki-main.c
  os/net/mac/tsch/tsch-queue.c
  os/net/mac/tsch/tsch-slot-operation.c
  os/net/mac/tsch/tsch-stats.c
  os/net/mac/tsch/tsch-stats.h
  os/net/mac/tsch/tsch.c
  os/net/mac/tsch/tsch.h
  os/services/tsch-cs/Makefile
  os/services/tsch-cs/tsch-cs.c
  os/services/tsch-cs/tsch-cs.h
Labels: pr/enhancement
