Repository contiki-ng/contiki-ng, pull requests merged in 2018-06, with the labels that each got.

#554 Docker image update from Travis
  .travis.yml
  tools/docker/Dockerfile
Labels: pr/enhancement

#566 Travis Docker push fix
  .travis.yml
Labels: pr/bugfix

#567 rx full IRQ handling for cc13xx/cc26xx
  arch/cpu/cc26xx-cc13xx/rf-core/prop-mode.c
  arch/cpu/cc26xx-cc13xx/rf-core/rf-core.c
  arch/cpu/cc26xx-cc13xx/rf-core/rf-core.h
Labels: bug/medium, pr/bugfix

#547 Add support for documentation on readthedocs.io
  .gitignore
  .travis.yml
  tests/00-documentation/Makefile
  tools/docker/Dockerfile
  tools/readthedocs/Makefile
  tools/readthedocs/api-doc.py
  tools/readthedocs/conf.py
  tools/readthedocs/index.rst
  tools/readthedocs/js/dynsections.js
Labels: documentation, pr/enhancement

#549 Deployment module
  examples/libs/deployment/Makefile
  examples/libs/deployment/README.md
  examples/libs/deployment/node.c
  examples/libs/deployment/project-conf.h
  examples/libs/deployment/sim.csc
  examples/libs/shell/example.c
  examples/libs/simple-energest/example.c
  os/net/ipv6/uip-sr.c
  os/net/routing/rpl-lite/rpl-neighbor.c
  os/services/deployment/deployment.c
  os/services/deployment/deployment.h
  os/services/deployment/module-macros.h
  os/sys/log-conf.h
  os/sys/log.c
  os/sys/log.h
  os/sys/node-id.c
  tests/03-compile-arm-ports-02/Makefile
Labels: pr/enhancement

#586 Specify default tun/tap name on Mac OS
  tools/serial-io/tunslip6.c
Labels: pr/bugfix

#585 Enable license auto-detection on github
  LICENSE.md
  README.md
Labels: documentation

#577 CoAP: unified request_state for both blocking and callback APIs and add status codes
  os/net/app-layer/coap/coap-blocking-api.c
  os/net/app-layer/coap/coap-blocking-api.h
  os/net/app-layer/coap/coap-callback-api.c
  os/net/app-layer/coap/coap-callback-api.h
  os/net/app-layer/coap/coap-request-state.h
  os/services/lwm2m/lwm2m-rd-client.c
Labels: pr/enhancement
