Repository contiki-ng/contiki-ng, pull requests merged in 2018-05, with the labels that each got.

#481 Make distclean: less verbose output
  Makefile.include
Labels: pr/enhancement

#462 Updated users of the SLIP driver to respect UIP_LLH_LEN
  examples/slip-radio/slip-radio.c
  os/services/ip64/ip64-slip-interface.c
  os/services/rpl-border-router/embedded/slip-bridge.c
Labels: pr/bugfix, pr/include-in-v4.1

#483 Check if a preferred parent exists before showing status in shell command 'rpl-status'
  os/services/shell/shell-commands.c
Labels: pr/bugfix, pr/include-in-v4.1

#486 Shorter log module names for CoAP/LWM2M/DTLS for nicer log output
  os/net/app-layer/coap/coap-block1.c
  os/net/app-layer/coap/coap-blocking-api.c
  os/net/app-layer/coap/coap-callback-api.c
  os/net/app-layer/coap/coap-observe-client.c
  os/net/app-layer/coap/coap-observe.c
  os/net/app-layer/coap/coap-res-well-known-core.c
  os/net/app-layer/coap/coap-separate.c
  os/net/app-layer/coap/coap-timer-default.c
  os/net/app-layer/coap/coap-transactions.c
  os/net/app-layer/coap/tinydtls-support/dtls-support.c
  os/services/lwm2m/lwm2m-device.c
  os/services/lwm2m/lwm2m-engine.c
  os/services/lwm2m/lwm2m-firmware.c
  os/services/lwm2m/lwm2m-plain-text.c
  os/services/lwm2m/lwm2m-rd-client.c
  os/services/lwm2m/lwm2m-security.c
  os/services/lwm2m/lwm2m-server.c
  os/services/lwm2m/lwm2m-tlv-writer.c
Labels: pr/include-in-v4.1

#484 Nullrouting: lowercase string description
  os/net/routing/nullrouting/nullrouting.c
Labels: pr/include-in-v4.1

#491 Improved default file size in Antelope
  os/storage/antelope/db-options.h
Labels: pr/include-in-v4.1

#432 Automatically resolve realpath of CONTIKI
  Makefile.include
Labels: bug, bug/low, pr/bugfix

#495 Updated lwm2m-ipso-object server-example for latest RPL/CoAP APIs
  examples/lwm2m-ipso-objects/Makefile
  examples/lwm2m-ipso-objects/README.md
  examples/lwm2m-ipso-objects/example-server.c
  examples/lwm2m-ipso-objects/serial-protocol.c
Labels: pr/bugfix, pr/include-in-v4.1

#505 Fixed driver for DHT22 sensor in zoul platform
  arch/platform/zoul/dev/dht22.c
  arch/platform/zoul/dev/dht22.h
  examples/platform-specific/zoul/Makefile
Labels: bug/low, pr/bugfix

#503 RPL Lite: disable MRHOF ETX squaring by default
  os/net/link-stats.c
  os/net/routing/rpl-classic/rpl-mrhof.c
  os/net/routing/rpl-lite/rpl-mrhof.c
Labels: pr/include-in-v4.1

#471 Easy switch to IBM Watson mode
  examples/mqtt-client/README.md
  examples/mqtt-client/mqtt-client.c
  examples/mqtt-client/project-conf.h
Labels: pr/enhancement

#504 RPL urgent probing fix
  os/net/routing/rpl-classic/rpl-dag.c
  os/net/routing/rpl-classic/rpl-private.h
  os/net/routing/rpl-classic/rpl-timers.c
  os/net/routing/rpl-classic/rpl.c
  os/net/routing/rpl-lite/rpl-neighbor.c
  os/net/routing/rpl-lite/rpl-timers.c
  os/net/routing/rpl-lite/rpl-timers.h
  os/net/routing/rpl-lite/rpl.c
Labels: bug/low, pr/bugfix

#507 Support for IEEE 802.15.4 short addresses
  arch/cpu/cc2538/ieee-addr.c
  examples/slip-radio/slip-radio.c
  os/net/ipv6/uip-ds6.c
  os/net/ipv6/uip.h
  os/services/rpl-border-router/embedded/slip-bridge.c
  os/services/rpl-border-router/native/border-router-cmds.c
  os/sys/log.c
Labels: pr/enhancement

#511 Extend usage string
  Makefile.include
Labels: pr/enhancement

#510 Add missing case statement
  tools/tools-utils.c
Labels: bug/low, pr/bugfix

#416 6LoWPAN fragment generation cleanup
  arch/platform/cooja/contiki-conf.h
  examples/slip-radio/slip-radio.c
  os/net/ipv6/sicslowpan.c
  os/net/ipv6/uip6.c
  os/services/rpl-border-router/native/border-router-mac.c
  tests/17-tun-rpl-br/08-border-router-cooja-frag.csc
  tests/17-tun-rpl-br/08-border-router-cooja-frag.sh
  tests/17-tun-rpl-br/test-border-router.sh
Labels: pr/enhancement

#516 Native border router SLIP fix
  os/services/rpl-border-router/native/slip-dev.c
  tests/17-tun-rpl-br/09-native-border-router-cooja-frag.sh
  tests/17-tun-rpl-br/test-native-border-router.sh
Labels: bug, bug/critical

#519 Added a configurable linker flag to enable linker warnings as errors
  Makefile.include
  arch/cpu/native/Makefile.native
Labels: pr/bugfix

#523 snprintf-based logging for IPv6 and RPL neighbor
  os/net/ipv6/uiplib.c
  os/net/ipv6/uiplib.h
  os/net/routing/rpl-lite/rpl-neighbor.c
  os/net/routing/rpl-lite/rpl-neighbor.h
  os/services/shell/shell-commands.c
  os/services/shell/shell.c
  os/sys/log.c
Labels: pr/enhancement

#534 Differentiate flash part across sensortag/cc2650 versions
  arch/platform/srf06-cc26xx/sensortag/cc2650/board.h
  examples/platform-specific/cc26xx/cc26xx-web-demo/README.md
  examples/platform-specific/cc26xx/cc26xx-web-demo/project-conf.h
Labels: bug/low, pr/bugfix

#393 Queue Mode implementation in LwM2M
  examples/lwm2m-ipso-objects/Makefile
  examples/lwm2m-ipso-objects/project-conf.h
  examples/lwm2m-ipso-objects/zoul/module-macros.h
  os/net/app-layer/coap/coap-observe.c
  os/net/app-layer/coap/coap-observe.h
  os/services/lwm2m/lwm2m-engine.c
  os/services/lwm2m/lwm2m-engine.h
  os/services/lwm2m/lwm2m-notification-queue.c
  os/services/lwm2m/lwm2m-notification-queue.h
  os/services/lwm2m/lwm2m-queue-mode-conf.h
  os/services/lwm2m/lwm2m-queue-mode-object.c
  os/services/lwm2m/lwm2m-queue-mode-object.h
  os/services/lwm2m/lwm2m-queue-mode.c
  os/services/lwm2m/lwm2m-queue-mode.h
  os/services/lwm2m/lwm2m-rd-client.c
  os/services/lwm2m/lwm2m-rd-client.h
  tests/01-compile-base/Makefile
  tests/02-compile-arm-ports-01/Makefile
  tests/03-compile-arm-ports-02/Makefile
  tests/18-coap-lwm2m/08-lwm2m-qmode-ipso-test.sh
  tests/18-coap-lwm2m/09-lwm2m-qmode-standalone-test.sh
  tests/18-coap-lwm2m/pytests/test-qmode-awake.py
  tests/18-coap-lwm2m/pytests/test-qmode-sleep.py
Labels: pr/enhancement

#548 Improve doxygen module structure and content
  arch/dev/ext-flash/ext-flash.c
  arch/dev/ext-flash/ext-flash.h
  os/net/ipv6/uiplib.c
  os/net/ipv6/uiplib.h
Labels: documentation

#512 Harmonize tools dir and the login, serialdump, serialview targets
  .gitignore
  Makefile.embedded
  Makefile.identify-target
  Makefile.include
  Makefile.tools
  arch/cpu/cc26xx-cc13xx/Makefile.cc26xx-cc13xx
  arch/platform/jn516x/Makefile.jn516x
  arch/platform/sky/Makefile.common
  arch/platform/zoul/Makefile.zoul
  os/services/rpl-border-router/embedded/Makefile.embedded
  tests/05-compile-tools/Makefile
  tools/Makefile
  tools/jn516x/Makefile
  tools/jn516x/serialdump-linux
  tools/jn516x/serialdump.c
  tools/serial-io/Makefile
  tools/serial-io/serialdump.c
  tools/serial-io/tools-utils.c
  tools/serial-io/tools-utils.h
  tools/serial-io/tunslip6.c
  tools/sky/Makefile
  tools/sky/serialdump-linux
  tools/sky/serialdump-macos
  tools/sky/serialdump-windows.exe
  tools/timestamp
Labels: pr/enhancement

#553 Use $(MAKE) instead of make to invoke recursively
  Makefile.include
  Makefile.tools
  tests/Makefile
  tests/Makefile.compile-test
Labels: pr/enhancement

#552 Remove makefsdata
  tools/makefsdata
Labels: pr/enhancement

#551 Move viewconf to its own dir
  Makefile.include
  tools/viewconf/viewconf.c
Labels: pr/enhancement

#550 Create the (failed) summary log even when sub-make fails
  tests/00-doxygen/Makefile
Labels: bug, bug/low, pr/bugfix
