Repository contiki-ng/contiki-ng, pull requests merged in 2018-10, with the labels that each got.

#688 Default to using os/lib/dbg-io for all arm-powered platforms
  arch/cpu/arm/Makefile.arm
  arch/cpu/cc2538/Makefile.cc2538
  arch/cpu/cc26xx-cc13xx/Makefile.cc26xx-cc13xx
  arch/cpu/simplelink-cc13xx-cc26xx/Makefile.cc13xx-cc26xx
  arch/platform/jn516x/Makefile.jn516x
  arch/platform/nrf52dk/Makefile.nrf52dk
Labels: pr/enhancement

#681 TSCH CCA
  os/net/mac/tsch/tsch-conf.h
  os/net/mac/tsch/tsch-slot-operation.c
Labels: pr/include-in-v4.2

#649 Add link stat packet counters
  os/net/link-stats.c
  os/net/link-stats.h
Labels: pr/include-in-v4.2

#562 Reworked busy-wait routines
  arch/dev/cc1200/cc1200.c
  arch/platform/cooja/dev/watchdog.c
  arch/platform/jn516x/dev/micromac-radio.c
  arch/platform/jn516x/dev/uart-driver.c
  arch/platform/zoul/dev/cc1200-zoul-arch.c
  arch/platform/zoul/dev/dht22.c
  os/net/mac/csma/csma-output.c
  os/net/mac/tsch/tsch-slot-operation.c
  os/net/mac/tsch/tsch.c
  os/net/mac/tsch/tsch.h
  os/sys/rtimer.h
Labels: pr/enhancement, pr/include-in-v4.2

#685 Improve usage of CCxxwares and CC2640R2 SDK
  arch/cpu/cc26xx-cc13xx/Makefile.cc13xx
  arch/cpu/cc26xx-cc13xx/Makefile.cc26x0r2f
  arch/cpu/cc26xx-cc13xx/Makefile.cc26xx
  arch/cpu/cc26xx-cc13xx/cc13xx-cc26xx-conf.h
  arch/cpu/cc26xx-cc13xx/dev/gpio-hal-arch.c
  arch/cpu/cc26xx-cc13xx/dev/gpio-hal-arch.h
  arch/cpu/cc26xx-cc13xx/dev/soc-rtc.c
  arch/cpu/cc26xx-cc13xx/dev/soc-trng.c
  arch/cpu/cc26xx-cc13xx/dev/spi-arch.c
  arch/cpu/cc26xx-cc13xx/lpm.c
  arch/cpu/cc26xx-cc13xx/rf-core/rf-core.c
  arch/cpu/cc26xx-cc13xx/ti-lib-rom.h
  arch/cpu/cc26xx-cc13xx/ti-lib.h
  arch/platform/srf06-cc26xx/launchpad/cc1350/rf-switch.c
  arch/platform/srf06-cc26xx/platform.c
  arch/platform/srf06-cc26xx/sensortag/mpu-9250-sensor.c
  arch/platform/srf06-cc26xx/srf06/als-sensor.c
  examples/platform-specific/cc26xx/cc26xx-web-demo/cc26xx-web-demo.h
Labels: pr/enhancement, pr/include-in-v4.2

#670 Provide default board for platform simplelink
  arch/platform/simplelink/Makefile.simplelink
Labels: bug/low, pr/bugfix, pr/include-in-v4.2

#671 Create platform-independent SPI select and deselect
  arch/cpu/cc2538/dev/spi-arch.c
  arch/cpu/cc26xx-cc13xx/dev/spi-arch.c
  arch/cpu/simplelink-cc13xx-cc26xx/dev/spi-arch.c
  os/dev/spi.c
Labels: pr/enhancement, pr/include-in-v4.2

#695 Remove obsolete function prototypes
  os/dev/spi.h
Labels: bug, bug/low, pr/bugfix, pr/include-in-v4.2

#697 Make sure CONTIKI_BOARD_xyz and CONTIKI_BOARD_STRING are defined
  Makefile.include
Labels: bug, bug/medium, pr/bugfix

#676 Add optimization flags for native builds
  arch/cpu/native/Makefile.native
Labels: pr/include-in-v4.2

#700 Detect boards automatically in the build-all script
  tests/compile-all/build.sh
Labels: pr/enhancement

#672 Harmonise link rule for all cortex CPUs
  arch/cpu/arm/cortex-m/Makefile.cortex-m
  arch/cpu/arm/cortex-m/cm3/Makefile.cm3
  arch/cpu/arm/cortex-m/cm4/Makefile.cm4
  arch/cpu/cc26xx-cc13xx/cc26xx.ld
  arch/cpu/nrf52832/ld/nrf52-pca10036-sd.ld
  arch/cpu/nrf52832/ld/nrf52-pca10040-sd.ld
  arch/cpu/nrf52832/ld/nrf52.ld
Labels: pr/enhancement, pr/include-in-v4.2

#702 MQTT buffer overflow fix
  os/net/app-layer/mqtt/mqtt.c
Labels: bug/vulnerability, pr/bugfix, pr/include-in-v4.2

#648 TSCH support for CC13xx
  arch/cpu/cc26xx-cc13xx/Makefile.cc13xx
  arch/cpu/cc26xx-cc13xx/cc13xx-cc26xx-def.h
  arch/cpu/cc26xx-cc13xx/rf-core/ble-hal/ble-hal-cc26xx.c
  arch/cpu/cc26xx-cc13xx/rf-core/cc13xx-50kbps-tsch.c
  arch/cpu/cc26xx-cc13xx/rf-core/cc13xx-50kbps-tsch.h
  arch/cpu/cc26xx-cc13xx/rf-core/ieee-mode.c
  arch/cpu/cc26xx-cc13xx/rf-core/prop-mode.c
  arch/cpu/cc26xx-cc13xx/rf-core/rf-core.c
  arch/cpu/cc26xx-cc13xx/rf-core/rf-core.h
  arch/cpu/cc26xx-cc13xx/ti-lib.h
  examples/6tisch/6p-packet/Makefile
  examples/6tisch/etsi-plugtest-2017/Makefile
  examples/6tisch/simple-node/Makefile
  examples/6tisch/sixtop/Makefile
  os/net/mac/tsch/tsch-const.h
Labels: pr/enhancement, pr/include-in-v4.2

#638 CC26xx RF: in polling mode, disable the CPE0 radio interrupt completely
  arch/cpu/cc26xx-cc13xx/rf-core/rf-core.c
Labels: bug/low, discussion, pr/include-in-v4.2

#699 Change platform zoul to use the new motelist
  Makefile.embedded
  Makefile.help
  Makefile.include
  arch/platform/zoul/Makefile.zoul
  arch/platform/zoul/firefly-reva/Makefile.firefly-reva
  arch/platform/zoul/firefly/Makefile.firefly
  arch/platform/zoul/orion/Makefile.orion
  arch/platform/zoul/remote-reva/Makefile.remote-reva
  arch/platform/zoul/remote-revb/Makefile.remote-revb
  tools/zolertia/license-bsl.txt
  tools/zolertia/motelist-zolertia
  tools/zolertia/motelist-zolertia-macos
Labels: pr/enhancement, pr/include-in-v4.2

#716 Fixed all-timers example application
  examples/libs/timers/all-timers.c
Labels: bug, bug/low, pr/bugfix, pr/include-in-v4.2

#632 CoAP: allow observations that do not timeout
  os/net/app-layer/coap/coap-conf.h
  os/net/app-layer/coap/coap-observe.c
Labels: pr/enhancement, pr/include-in-v4.2

#683 Improve GPIO HAL when used with 64-bit pin masks
  examples/dev/gpio-hal/gpio-hal-example.c
  os/dev/gpio-hal.h
Labels: bug, bug/medium, pr/bugfix, pr/include-in-v4.2

#711 tsch: handle failure in prepare()
  os/net/mac/tsch/tsch-slot-operation.c
Labels: bug, bug/medium, pr/bugfix, pr/include-in-v4.2

#723 Add MQTT client execution test
  examples/mqtt-client/mqtt-client.c
  examples/mqtt-client/project-conf.h
  tests/08-native-runs/02-mqtt-client.sh
Labels: pr/enhancement, pr/include-in-v4.2

#720 Reduce docker image build verbosity
  tools/docker/Dockerfile
Labels: pr/enhancement, pr/include-in-v4.2

#717 Add out of tree build tests
  .travis.yml
  tests/19-out-of-tree-build/Makefile
Labels: pr/enhancement, pr/include-in-v4.2

#703 Json library: fix a number of potential buffer overflows
  os/lib/json/jsonparse.c
  os/lib/json/jsontree.c
Labels: bug/vulnerability, pr/bugfix, pr/include-in-v4.2

#401 Introduce UIP_DS6_NBR_MULTI_IPV6_ADDRS
  .travis.yml
  examples/platform-specific/cc26x0-cc13x0/cc26x0-web-demo/httpd-simple.c
  examples/platform-specific/zoul/orion/ip64-router/ip64-router.c
  examples/rpl-border-router/webserver/webserver.c
  os/net/ipv6/uip-ds6-nbr.c
  os/net/ipv6/uip-ds6-nbr.h
  os/net/routing/rpl-classic/rpl-dag.c
  os/net/routing/rpl-classic/rpl-nbr-policy.c
  os/net/routing/rpl-classic/rpl.h
  os/net/routing/rpl-lite/rpl-nbr-policy.c
  os/net/routing/rpl-lite/rpl-neighbor.c
  tests/09-ipv6/09-ping-lla-ula-csma-w-rpl.csc
  tests/09-ipv6/10-ping-lla-ula-tsch-w-rpl.csc
  tests/09-ipv6/11-ping-lla-ula-csma-wo-rpl.csc
  tests/09-ipv6/12-ping-lla-ula-tsch-wo-rpl.csc
  tests/09-ipv6/code/Makefile
  tests/09-ipv6/js/ping-test-lla-ula.js
  tests/10-ipv6-nbr/01-test-nbr-multi-addrs.sh
  tests/10-ipv6-nbr/Makefile
  tests/10-ipv6-nbr/nbr-multi-addrs/Makefile
  tests/10-ipv6-nbr/nbr-multi-addrs/test.c
Labels: pr/enhancement, pr/work-in-progress

#714 Safer uIP6 buffer handling
  arch/cpu/msp430/uip-ipchksum.c
  arch/cpu/native/net/tun6-net.c
  arch/platform/cooja/net/uip-driver.c
  arch/platform/jn516x/slip.c
  examples/libs/ipv6-hooks/ipv6-hooks.c
  examples/multicast/sink.c
  examples/platform-specific/jn516x/tsch/common-conf-jn516x.h
  examples/platform-specific/jn516x/tsch/simple-sensor-network/node/node.c
  examples/platform-specific/nrf52dk/coap-demo/coap-server/coap-server.c
  examples/slip-radio/slip-radio.c
  os/contiki-net.h
  os/dev/slip.c
  os/net/app-layer/coap/coap-uip.c
  os/net/ipv6/multicast/esmrf.c
  os/net/ipv6/multicast/roll-tm.c
  os/net/ipv6/multicast/smrf.c
  os/net/ipv6/resolv.c
  os/net/ipv6/sicslowpan.c
  os/net/ipv6/simple-udp.c
  os/net/ipv6/tcpip.c
  os/net/ipv6/udp-socket.c
  os/net/ipv6/uip-icmp6.c
  os/net/ipv6/uip-icmp6.h
  os/net/ipv6/uip-nameserver.c
  os/net/ipv6/uip-nd6.c
  os/net/ipv6/uip-packetqueue.h
  os/net/ipv6/uip-udp-packet.c
  os/net/ipv6/uip.h
  os/net/ipv6/uip6.c
  os/net/ipv6/uipbuf.c
  os/net/ipv6/uipbuf.h
  os/net/ipv6/uiplib.c
  os/net/ipv6/uiplib.h
  os/net/ipv6/uipopt.h
  os/net/routing/nullrouting/nullrouting.c
  os/net/routing/routing.h
  os/net/routing/rpl-classic/rpl-ext-header.c
  os/net/routing/rpl-classic/rpl-icmp6.c
  os/net/routing/rpl-classic/rpl-nbr-policy.c
  os/net/routing/rpl-classic/rpl.h
  os/net/routing/rpl-lite/rpl-ext-header.c
  os/net/routing/rpl-lite/rpl-ext-header.h
  os/net/routing/rpl-lite/rpl-icmp6.c
  os/net/routing/rpl-lite/rpl-nbr-policy.c
  os/services/ip64/ip64-arp.c
  os/services/ip64/ip64-dhcpc.c
  os/services/ip64/ip64-eth-interface.c
  os/services/ip64/ip64-slip-interface.c
  os/services/rpl-border-router/embedded/slip-bridge.c
  os/services/rpl-border-router/native/tun-bridge.c
  tools/sky/uip6-bridge/Makefile
  tools/sky/uip6-bridge/dev/slip.c
  tools/sky/uip6-bridge/dev/slip.h
  tools/sky/uip6-bridge/fakeuip.c
  tools/sky/uip6-bridge/project-conf.h
  tools/sky/uip6-bridge/radvd.conf
  tools/sky/uip6-bridge/sicslow_ethernet.c
  tools/sky/uip6-bridge/sicslow_ethernet.h
  tools/sky/uip6-bridge/uip6-bridge-tap.c
  tools/wpcapslip/wpcap.c
Labels: bug/vulnerability, pr/bugfix, pr/enhancement
