Repository contiki-ng/contiki-ng, pull requests merged in 2018-03, with the labels that each got.

#251 BLEach a fully open-source IPv6-over-BLE stack for the TI CC26xx platform
  Makefile.include
  arch/cpu/cc26xx-cc13xx/Makefile.cc26xx-cc13xx
  arch/cpu/cc26xx-cc13xx/ble-addr.c
  arch/cpu/cc26xx-cc13xx/ble-addr.h
  arch/cpu/cc26xx-cc13xx/cc13xx-cc26xx-conf.h
  arch/cpu/cc26xx-cc13xx/rf-core/README.md
  arch/cpu/cc26xx-cc13xx/rf-core/ble-cc2650.c
  arch/cpu/cc26xx-cc13xx/rf-core/ble-hal/ble-hal-cc26xx.c
  arch/cpu/cc26xx-cc13xx/rf-core/ble-hal/ble-hal-cc26xx.h
  arch/cpu/cc26xx-cc13xx/rf-core/ble-hal/rf-ble-cmd.c
  arch/cpu/cc26xx-cc13xx/rf-core/ble-hal/rf-ble-cmd.h
  arch/platform/srf06-cc26xx/platform.c
  examples/ble/ipv6-client/Makefile
  examples/ble/ipv6-client/client.c
  examples/ble/ipv6-client/project-conf.h
  os/dev/ble-hal.h
  os/net/mac/ble/ble-l2cap.c
  os/net/mac/ble/ble-l2cap.h
  os/net/netstack.h
  tests/02-compile-arm-ports-01/Makefile
Labels: pr/enhancement

#347 Fix build error and tidy-up BLE example
  arch/cpu/cc26xx-cc13xx/rf-core/ble-cc2650.c
  examples/ble/ipv6-client/Makefile
  examples/platform-specific/cc26xx/ble-ipv6/Makefile
  examples/platform-specific/cc26xx/ble-ipv6/README.md
  examples/platform-specific/cc26xx/ble-ipv6/client.c
  examples/platform-specific/cc26xx/ble-ipv6/project-conf.h
  tests/02-compile-arm-ports-01/Makefile
Labels: bug/medium, documentation, pr/bugfix

#345 Only print RADIO_PARAM_PAN_ID at startup if the radio supports it
  arch/platform/srf06-cc26xx/platform.c
Labels: bug/low, pr/bugfix

#286 Add Vagrant support
  tools/vagrant/.gitignore
  tools/vagrant/README.md
  tools/vagrant/Vagrantfile
  tools/vagrant/bootstrap.sh
Labels: pr/enhancement

#356 Fix link layer address retrieval from flash
  arch/platform/srf06-cc26xx/platform.c
Labels: pr/bugfix

#362 TSCH Keepalive loop fix
  os/net/mac/tsch/tsch.c
Labels: pr/bugfix

#368 Fix launchpad LED colour mappings
  arch/platform/srf06-cc26xx/launchpad/cc1310/board.h
  arch/platform/srf06-cc26xx/launchpad/cc1350/board.h
  arch/platform/srf06-cc26xx/launchpad/cc2650/board.h
Labels: bug/low, pr/bugfix

#304 Fix observer and block-wise transfer interaction
  os/net/app-layer/coap/coap-engine.c
  os/net/app-layer/coap/coap-observe.c
Labels: pr/bugfix

#379 Cleanup TSCH .h files
  examples/6tisch/6p-packet/test-sf.c
  examples/6tisch/etsi-plugtest-2017/node.c
  examples/6tisch/simple-node/node.c
  examples/6tisch/sixtop/node-sixtop.c
  examples/6tisch/sixtop/sf-simple.c
  examples/platform-specific/jn516x/tsch/simple-sensor-network/node/node.c
  examples/platform-specific/jn516x/tsch/tx-power-verification/rpl-border-router/rpl-border-router.c
  os/net/mac/framer/frame802154e-ie.h
  os/net/mac/tsch/tsch-adaptive-timesync.c
  os/net/mac/tsch/tsch-adaptive-timesync.h
  os/net/mac/tsch/tsch-conf.h
  os/net/mac/tsch/tsch-const.h
  os/net/mac/tsch/tsch-log.c
  os/net/mac/tsch/tsch-log.h
  os/net/mac/tsch/tsch-packet.c
  os/net/mac/tsch/tsch-packet.h
  os/net/mac/tsch/tsch-private.h
  os/net/mac/tsch/tsch-queue.c
  os/net/mac/tsch/tsch-queue.h
  os/net/mac/tsch/tsch-rpl.c
  os/net/mac/tsch/tsch-rpl.h
  os/net/mac/tsch/tsch-schedule.c
  os/net/mac/tsch/tsch-schedule.h
  os/net/mac/tsch/tsch-security.c
  os/net/mac/tsch/tsch-security.h
  os/net/mac/tsch/tsch-slot-operation.c
  os/net/mac/tsch/tsch-slot-operation.h
  os/net/mac/tsch/tsch-types.h
  os/net/mac/tsch/tsch.c
  os/net/mac/tsch/tsch.h
  os/services/orchestra/orchestra.h
  os/services/shell/shell-commands.c
  tests/13-ieee802154/code-6tisch/test-sixp-pkt.c
  tests/13-ieee802154/code-flush-nbr-queue/test-flush-nbr-queue.c
  tools/viewconf.c
Labels: pr/enhancement, pr/include-in-v4.1

#310 CC26xx: increase size of the region reserved for stack from 256 bytes to 1024 bytes
  arch/cpu/cc26xx-cc13xx/cc26xx.ld
  examples/platform-specific/cc26xx/cc26xx-web-demo/project-conf.h
Labels: pr/enhancement, pr/include-in-v4.1

#357 Update 6top Protocol (6P) to draft-10
  examples/6tisch/6p-packet/project-conf.h
  examples/6tisch/6p-packet/sixp-node.c
  examples/6tisch/6p-packet/test-sf.c
  examples/6tisch/etsi-plugtest-2017/sf-plugtest.c
  examples/6tisch/sixtop/sf-simple.c
  os/net/mac/tsch/sixtop/sixp-nbr.c
  os/net/mac/tsch/sixtop/sixp-nbr.h
  os/net/mac/tsch/sixtop/sixp-pkt.c
  os/net/mac/tsch/sixtop/sixp-pkt.h
  os/net/mac/tsch/sixtop/sixp-trans.c
  os/net/mac/tsch/sixtop/sixp.c
  tests/13-ieee802154/code-6tisch/test-sixp-nbr.c
  tests/13-ieee802154/code-6tisch/test-sixp-pkt.c
  tests/13-ieee802154/code-6tisch/test-sixp-trans.c
  tests/13-ieee802154/code-6tisch/test-sixp.c
Labels: pr/enhancement, pr/include-in-v4.1
