Repository contiki-ng/contiki-ng, pull requests merged in 2018-04, with the labels that each got.

#407 Add some build artifacts to .gitignore
  .gitignore
Labels: pr/enhancement

#405 Allow the LED HAL to work on platforms without LEDs
  os/dev/leds.c
Labels: pr/enhancement

#403 Remove obsolete typedefs from platform native
  arch/platform/native/contiki-conf.h
Labels: pr/enhancement

#402 Add some logging to the GPIO HAL
  os/dev/gpio-hal.c
Labels: pr/enhancement

#397 Allow the MQTT client to build & work without platform-specific extensions
  examples/mqtt-client/arch/platform/cc2538dk/module-macros.h
  examples/mqtt-client/arch/platform/openmote-cc2538/module-macros.h
  examples/mqtt-client/arch/platform/srf06-cc26xx/module-macros.h
  examples/mqtt-client/arch/platform/zoul/module-macros.h
  examples/mqtt-client/mqtt-client.c
Labels: pr/enhancement

#406 Fix CONTIKI_TARGET_STRING
  Makefile.include
Labels: bug/low, pr/bugfix

#394 Delete jn516x-specific BR example
  arch/platform/jn516x/jn516x-def.h
  arch/platform/jn516x/lib/slip.c
  examples/platform-specific/jn516x/tsch/tx-power-verification/rpl-border-router/Makefile
  examples/platform-specific/jn516x/tsch/tx-power-verification/rpl-border-router/project-conf.h
  examples/platform-specific/jn516x/tsch/tx-power-verification/rpl-border-router/rpl-border-router.c
  examples/platform-specific/jn516x/tsch/tx-power-verification/rpl-border-router/slip-bridge.c
  tests/04-compile-nxp-ports/Makefile
Labels: pr/enhancement

#399 Use os/lib/dbg-io for platform jn516x
  arch/platform/jn516x/Makefile.jn516x
  arch/platform/jn516x/dbg.c
  arch/platform/jn516x/lib/sprintf.c
  arch/platform/jn516x/slip.c
Labels: pr/enhancement

#414 Various logging improvements
  examples/slip-radio/slip-radio.c
  os/net/app-layer/coap/coap-engine.c
  os/net/app-layer/coap/coap-uip.c
  os/net/ipv6/sicslowpan.c
  os/net/ipv6/tcpip.c
  os/net/mac/csma/csma-output.c
  os/net/mac/csma/csma.c
Labels: pr/enhancement

#412 CSMA fixes
  os/net/mac/csma/csma-output.c
Labels: pr/bugfix

#410 Shell: added ability to trigger a RPL DTSN increment
  os/net/routing/rpl-lite/rpl-dag.c
  os/net/routing/rpl-lite/rpl.h
  os/services/shell/shell-commands.c
Labels: pr/enhancement

#404 Tidy-up AROPTS for cpu native
  arch/cpu/native/Makefile.native
  arch/platform/native/Makefile.native
Labels: bug/low, pr/bugfix, pr/enhancement

#400 Emulate interrupt manipulation on native
  arch/cpu/native/Makefile.native
  arch/cpu/native/int-master.c
Labels: pr/enhancement, pr/include-in-v4.1

#385 Bugfix on Address Resolution by Neighbor Discovery Protocol
  .travis.yml
  os/net/ipv6/uip-ds6-nbr.c
  os/net/ipv6/uip-ds6-nbr.h
  os/net/ipv6/uip-nd6.c
  os/net/nbr-table.c
  os/net/nbr-table.h
  tests/09-ipv6/01-ping-lla-csma-w-rpl.csc
  tests/09-ipv6/02-ping-ula-csma-w-rpl.csc
  tests/09-ipv6/03-ping-lla-tsch-w-rpl.csc
  tests/09-ipv6/04-ping-ula-tsch-w-rpl.csc
  tests/09-ipv6/05-ping-lla-csma-wo-rpl.csc
  tests/09-ipv6/06-ping-ula-csma-wo-rpl.csc
  tests/09-ipv6/07-ping-lla-tsch-wo-rpl.csc
  tests/09-ipv6/08-ping-ula-tsch-wo-rpl.csc
  tests/09-ipv6/Makefile
  tests/09-ipv6/code/Makefile
  tests/09-ipv6/code/node.c
  tests/09-ipv6/js/ping-test-lla.js
  tests/09-ipv6/js/ping-test-ula.js
Labels: bug/low, pr/bugfix

#422 Remove trailing whitespaces and other code style fixes
  README.md
  arch/cpu/cc2538/dev/spi-arch-legacy.h
  arch/cpu/msp430/f1xxx/spi-legacy.c
  arch/cpu/msp430/msp430-def.h
  arch/dev/ext-flash/ext-flash.c
  arch/platform/cc2538dk/dev/leds-arch.c
  arch/platform/openmote-cc2538/dev/leds-arch.c
  arch/platform/srf06-cc26xx/cfs-coffee-arch.h
  arch/platform/srf06-cc26xx/common/xmem.c
  arch/platform/srf06-cc26xx/launchpad/leds-arch.c
  arch/platform/srf06-cc26xx/sensortag/cc1350/leds-arch.c
  arch/platform/srf06-cc26xx/sensortag/cc2650/leds-arch.c
  arch/platform/srf06-cc26xx/srf06/leds-arch.c
  arch/platform/zoul/dev/leds-arch.c
  examples/platform-specific/cc26xx/ble-ipv6/README.md
  os/lib/dbg-io/strformat.h
  os/net/routing/rpl-classic/rpl-dag.c
  os/sys/stack-check.h
  tests/07-simulation-base/js/04-ringbufindex.js
  tests/07-simulation-base/js/22-stack-check.js
  tests/13-ieee802154/js/sixtop-test.js
Labels: pr/enhancement, pr/include-in-v4.1

#427 6LoWPAN avoid buffer overflow in case of IPv6 header larger than packetbuf
  os/net/ipv6/sicslowpan.c
Labels: pr/bugfix, pr/include-in-v4.1, pr/review needed

#411 CoAP: enable calling coap_get_payload with a NULL pointer
  os/net/app-layer/coap/coap.c
Labels: bug/low, pr/bugfix, pr/include-in-v4.1

#415 CoAP: auto-initialize module
  examples/coap/coap-example-client.c
  examples/coap/coap-example-server.c
  examples/coap/plugtest-server.c
  examples/ipso-objects/example-server.c
  examples/platform-specific/cc26xx/cc26xx-web-demo/coap-server.c
  examples/platform-specific/cc26xx/very-sleepy-demo/very-sleepy-demo.c
  examples/platform-specific/jn516x/rpl/coap-dongle-node/dongle-node.c
  examples/platform-specific/jn516x/rpl/coap-dr1175-node/dr1175-node.c
  examples/platform-specific/jn516x/rpl/coap-dr1199-node/dr1199-node.c
  examples/platform-specific/jn516x/tsch/tx-power-verification/node/node.c
  examples/platform-specific/jn516x/tsch/uart1-test-node/uart1-test-node.c
  examples/platform-specific/nrf52dk/coap-demo/coap-client/coap-client.c
  examples/platform-specific/nrf52dk/coap-demo/coap-server/coap-server.c
  os/contiki-main.c
  os/net/app-layer/coap/coap-engine.c
  os/net/app-layer/coap/coap.c
  os/net/app-layer/coap/module-macros.h
  os/services/lwm2m/lwm2m-engine.c
Labels: pr/enhancement

#372 RPL Lite: reset trickle when hearing old versions from the root
  os/net/routing/rpl-lite/rpl-dag.c
Labels: pr/include-in-v4.1

#430 Added check for block offset overflow in CoAP block2 requests.
  os/net/app-layer/coap/coap-engine.c
Labels: pr/bugfix, pr/include-in-v4.1

#433 Homogenize IEEE 802.15.4 channel configuration
  arch/cpu/cc2538/cc2538-conf.h
  arch/cpu/cc2538/dev/cc2538-rf.c
  arch/cpu/cc2538/dev/cc2538-rf.h
  arch/cpu/cc26xx-cc13xx/cc13xx-cc26xx-conf.h
  arch/cpu/cc26xx-cc13xx/rf-core/ieee-mode.c
  arch/cpu/cc26xx-cc13xx/rf-core/prop-mode.c
  arch/cpu/cc26xx-cc13xx/rf-core/rf-core.h
  arch/dev/cc2420/cc2420.c
  arch/dev/cc2420/cc2420.h
  arch/platform/cc2538dk/platform.c
  arch/platform/cooja/contiki-conf.h
  arch/platform/jn516x/contiki-conf.h
  arch/platform/jn516x/dev/micromac-radio.c
  arch/platform/openmote-cc2538/platform.c
  arch/platform/sky/contiki-conf.h
  arch/platform/sky/platform.c
  arch/platform/srf06-cc26xx/platform.c
  arch/platform/zoul/platform.c
  examples/coap/coap-example-server.c
  examples/coap/plugtest-server.c
  examples/coap/project-conf.h
  examples/platform-specific/cc26xx/cc26xx-web-demo/project-conf.h
  examples/platform-specific/cc26xx/project-conf.h
  examples/platform-specific/cc26xx/very-sleepy-demo/project-conf.h
  examples/platform-specific/jn516x/rpl/common-conf.h
  examples/platform-specific/jn516x/tsch/common-conf.h
  examples/rpl-udp/rpl-udp-sky.csc
  os/contiki-default-conf.h
  os/contiki-main.c
  os/net/mac/mac.h
  os/net/routing/nullrouting/nullrouting.c
  tools/viewconf.c
Labels: pr/enhancement

#418 A variety of minor RPL enhancements
  os/net/routing/rpl-lite/rpl-dag.c
  os/net/routing/rpl-lite/rpl-timers.c
  os/services/shell/shell-commands.c
Labels: pr/enhancement, pr/include-in-v4.1

#428 RPL Lite: fix handling of max rank on 16-bit platforms
  os/net/routing/rpl-lite/rpl-neighbor.c
Labels: pr/bugfix, pr/include-in-v4.1

#423 Reworking examples directory structure
  examples/ipso-objects/README.md
  examples/libs/ipv6-hooks/Makefile
  examples/libs/ipv6-hooks/README.md
  examples/libs/ipv6-hooks/ipv6-hooks.c
  examples/lwm2m-ipso-objects/Makefile
  examples/lwm2m-ipso-objects/README.md
  examples/lwm2m-ipso-objects/example-ipso-objects.c
  examples/lwm2m-ipso-objects/example-ipso-temperature.c
  examples/lwm2m-ipso-objects/example-server.c
  examples/lwm2m-ipso-objects/project-conf.h
  examples/lwm2m-ipso-objects/serial-protocol.c
  examples/lwm2m-ipso-objects/serial-protocol.h
  examples/websocket/Makefile
  examples/websocket/http-example.c
  examples/websocket/project-conf.h
  examples/websocket/websocket-example.c
  examples/websocket/websocket-node/Makefile
  examples/websocket/websocket-node/example-server.js
  tests/01-compile-base/Makefile
  tests/02-compile-arm-ports-01/Makefile
  tests/03-compile-arm-ports-02/Makefile
  tests/18-coap-lwm2m/06-lwm2m-ipso-test.sh
Labels: pr/enhancement, pr/include-in-v4.1

#443 Fixing cc26xx 6lbr client example
  examples/platform-specific/cc26xx/cc26xx-web-demo/Makefile
  examples/platform-specific/cc26xx/cc26xx-web-demo/cetic-6lbr-client.c
  examples/platform-specific/cc26xx/cc26xx-web-demo/project-conf.h
  tests/02-compile-arm-ports-01/Makefile
Labels: pr/bugfix, pr/include-in-v4.1

#421 Doxygen documentation for TSCH
  os/net/mac/tsch/tsch-adaptive-timesync.h
  os/net/mac/tsch/tsch-asn.h
  os/net/mac/tsch/tsch-log.h
  os/net/mac/tsch/tsch-packet.c
  os/net/mac/tsch/tsch-packet.h
  os/net/mac/tsch/tsch-queue.h
  os/net/mac/tsch/tsch-rpl.h
  os/net/mac/tsch/tsch-schedule.h
  os/net/mac/tsch/tsch-slot-operation.h
  os/net/mac/tsch/tsch-types.h
  os/net/mac/tsch/tsch.h
Labels: pr/include-in-v4.1

#445 Remove leftover COOJA_IP64 flags
  os/net/mac/csma/csma-output.c
Labels: pr/include-in-v4.1

#454 uiplib: ensure output string is null-terminated when printing the unspecified address
  os/net/ipv6/uiplib.c
Labels: pr/bugfix, pr/include-in-v4.1

#456 Shell client with history
  arch/cpu/cc26xx-cc13xx/Makefile.cc26xx-cc13xx
  arch/platform/jn516x/Makefile.jn516x
  arch/platform/sky/Makefile.common
  arch/platform/zoul/Makefile.zoul
  os/services/rpl-border-router/native/Makefile.native
  tools/docker/Dockerfile
  tools/vagrant/bootstrap.sh
Labels: pr/enhancement

#461 Added a periodic timer to the hello-world example
  examples/hello-world/hello-world.c
Labels: pr/include-in-v4.1

#464 Fix the multicast example for sensortags
  examples/multicast/project-conf.h
  examples/multicast/srf06-cc26xx/module-macros.h
Labels: pr/bugfix, pr/include-in-v4.1

#467 Update the CoAP section of the cc26xx web demo readme
  examples/platform-specific/cc26xx/cc26xx-web-demo/README.md
  examples/platform-specific/cc26xx/cc26xx-web-demo/img/coap-resources.png
Labels: documentation, pr/include-in-v4.1
