Repository contiki-ng/contiki-ng, pull requests merged in 2019-09, with the labels that each got.

#1039 Change default tunslip6 verbosity
  tools/serial-io/tunslip6.c
Labels: bug, bug/low, pr/bugfix, pr/include-in-v4.4

#1041 Fix location of misleading comment
  os/net/routing/rpl-lite/rpl-dag.c
Labels: bug, bug/low, documentation, pr/bugfix, pr/include-in-v4.4

#1042 Add support for the .upload make target for platform simplelink
  arch/cpu/simplelink-cc13xx-cc26xx/Makefile.cc13xx-cc26xx
Labels: bug, bug/low, pr/bugfix, pr/include-in-v4.4

#1043 Replace the multicast example simulation file
  examples/multicast/multicast.csc
Labels: pr/bugfix, pr/include-in-v4.4

#1049 TSCH: do not send EB packets when in leaf mode
  os/net/mac/tsch/tsch.c
  os/net/routing/nullrouting/nullrouting.c
  os/net/routing/routing.h
  os/net/routing/rpl-classic/rpl.c
  os/net/routing/rpl-classic/rpl.h
  os/net/routing/rpl-lite/rpl.c
Labels: pr/include-in-v4.4

#1051 minor improvements and cleanups in TSCH
  os/net/mac/tsch/tsch-adaptive-timesync.c
  os/net/mac/tsch/tsch-adaptive-timesync.h
  os/net/mac/tsch/tsch-queue.c
  os/net/mac/tsch/tsch-slot-operation.c
  os/net/mac/tsch/tsch.c
Labels: pr/include-in-v4.4

#1057 Assorted minor Orchestra bugfixes and features
  os/net/mac/tsch/tsch.h
  os/services/orchestra/orchestra-rule-default-common.c
  os/services/orchestra/orchestra-rule-eb-per-time-source.c
  os/services/orchestra/orchestra-rule-unicast-per-neighbor-rpl-ns.c
  os/services/orchestra/orchestra-rule-unicast-per-neighbor-rpl-storing.c
  os/services/orchestra/orchestra.c
  os/services/orchestra/orchestra.h
Labels: pr/include-in-v4.4

#1045 Fix for the SD/MMC driver of Zolertia RE-Mote
  arch/platform/zoul/dev/mmc-arch.c
Labels: bug, bug/low, pr/bugfix, pr/include-in-v4.4

#1060 Add support for MQTT 3.1.1
  examples/mqtt-client/mqtt-client.c
  examples/platform-specific/cc26x0-cc13x0/cc26x0-web-demo/mqtt-client.c
  examples/platform-specific/nrf52dk/mqtt-demo/mqtt-demo.c
  os/net/app-layer/mqtt/mqtt.c
  os/net/app-layer/mqtt/mqtt.h
  tests/08-native-runs/02-mqtt-client-31.sh
  tests/08-native-runs/03-mqtt-client-31-valgrind.sh
  tests/08-native-runs/04-mqtt-client-311.sh
  tests/08-native-runs/05-mqtt-client-311-valgrind.sh
  tests/08-native-runs/mqtt-client.sh
  tests/utils.sh
  tools/docker/Dockerfile
Labels: pr/enhancement, pr/include-in-v4.4

#1015 RPL-Lite: don't reset DIO timer if the current interval is equal to Imin
  os/net/routing/rpl-lite/rpl-dag.c
  os/net/routing/rpl-lite/rpl-timers.c
  tests/14-rpl-lite/10-rpl-resetting-dio-timer-by-dis.csc
  tests/14-rpl-lite/code/Makefile
  tests/14-rpl-lite/code/dis-sender.c
  tests/14-rpl-lite/code/project-conf.h
  tests/14-rpl-lite/js/10-rpl-setting-dio-timer-by-dis.js
  tests/15-rpl-classic/11-rpl-resetting-dio-timer-by-dis.csc
  tests/15-rpl-classic/code/Makefile
  tests/15-rpl-classic/code/dis-sender.c
  tests/15-rpl-classic/code/project-conf.h
  tests/15-rpl-classic/js/11-rpl-setting-dio-timer-by-dis.js
Labels: bug

#1073 Remove firmware files
  examples/hello-world/hello-world.nrf52840dk
  examples/rpl-border-router/border-router.nrf52840dk
Labels: bug, bug/low, pr/bugfix, pr/include-in-v4.4

#972 sicslowpan vulnerability fixes
  os/net/ipv6/sicslowpan.c
Labels: bug/vulnerability, pr/bugfix, pr/include-in-v4.4

#1044 Add new GPIO, button and LED HAL support to platform Cooja
  arch/platform/cooja/Makefile.cooja
  arch/platform/cooja/contiki-conf.h
  arch/platform/cooja/dev/button-sensor.c
  arch/platform/cooja/dev/button-sensor.h
  arch/platform/cooja/dev/buttons.c
  arch/platform/cooja/dev/gpio-hal-arch.c
  arch/platform/cooja/dev/gpio-hal-arch.h
  arch/platform/cooja/dev/leds-arch.c
  arch/platform/cooja/platform.c
  examples/dev/button-hal/Makefile
  examples/dev/gpio-hal/Makefile
  examples/dev/gpio-hal/cooja/pins.c
Labels: pr/enhancement, pr/include-in-v4.4

#1020 Implemented Snmp v1 and v2c
  examples/snmp-server/Makefile
  examples/snmp-server/project-conf.h
  examples/snmp-server/resources/snmp-SNMP-MIB-2-System.c
  examples/snmp-server/snmp-server.c
  os/contiki-main.c
  os/net/app-layer/snmp/module-macros.h
  os/net/app-layer/snmp/snmp-api.c
  os/net/app-layer/snmp/snmp-api.h
  os/net/app-layer/snmp/snmp-ber.c
  os/net/app-layer/snmp/snmp-ber.h
  os/net/app-layer/snmp/snmp-conf.h
  os/net/app-layer/snmp/snmp-engine.c
  os/net/app-layer/snmp/snmp-engine.h
  os/net/app-layer/snmp/snmp-message.c
  os/net/app-layer/snmp/snmp-message.h
  os/net/app-layer/snmp/snmp-mib.c
  os/net/app-layer/snmp/snmp-mib.h
  os/net/app-layer/snmp/snmp-oid.c
  os/net/app-layer/snmp/snmp-oid.h
  os/net/app-layer/snmp/snmp.c
  os/net/app-layer/snmp/snmp.h
  os/sys/log-conf.h
  os/sys/log.c
  os/sys/log.h
  tests/01-compile-base/Makefile
  tests/02-compile-arm-ports-01/Makefile
  tests/08-native-runs/06-snmp-server.sh
  tools/docker/Dockerfile
  tools/viewconf/viewconf.c
Labels: pr/enhancement, pr/include-in-v4.4

#1047 fix initialization of link stats
  os/net/link-stats.c
Labels: bug, pr/include-in-v4.4
