Repository contiki-ng/contiki-ng, pull requests merged in 2019-10, with the labels that each got.

#589 Fix broken rtimer for native
  arch/cpu/native/rtimer-arch.c
Labels: pr/bugfix, pr/include-in-v4.4

#1083 Improve read_frame and pending_packet consistency in the cc13x0 prop mode driver
  arch/cpu/cc26x0-cc13x0/rf-core/prop-mode.c
Labels: pr/bugfix, pr/include-in-v4.4

#1085 travis: specify Trusty explicitly to avoid Xenial
  .travis.yml
Labels: pr/bugfix

#1082 Add readthedocs status badge
  README.md
Labels: pr/enhancement, pr/include-in-v4.4

#1023 docker: fix an issue on net.ipv6.conf.all.disable_ipv6
  .travis.yml
  tools/docker/Dockerfile
Labels: bug, bug/medium, pr/bugfix, pr/include-in-v4.4

#1080 Initial support for board OpenMote-B
  .gitignore
  arch/platform/openmote/Makefile.openmote
  arch/platform/openmote/contiki-conf.h
  arch/platform/openmote/dev/adxl346.c
  arch/platform/openmote/dev/adxl346.h
  arch/platform/openmote/dev/antenna.c
  arch/platform/openmote/dev/antenna.h
  arch/platform/openmote/dev/max44009.c
  arch/platform/openmote/dev/max44009.h
  arch/platform/openmote/dev/openmote-sensors.c
  arch/platform/openmote/dev/openmote-sensors.h
  arch/platform/openmote/dev/sht21.c
  arch/platform/openmote/dev/sht21.h
  arch/platform/openmote/dev/tps62730.c
  arch/platform/openmote/dev/tps62730.h
  arch/platform/openmote/doxygen-group.txt
  arch/platform/openmote/openmote-b/board-buttons.c
  arch/platform/openmote/openmote-b/board.c
  arch/platform/openmote/openmote-b/board.h
  arch/platform/openmote/openmote-b/leds-arch.c
  arch/platform/openmote/openmote-cc2538/Makefile.openmote-cc2538
  arch/platform/openmote/openmote-cc2538/board-buttons.c
  arch/platform/openmote/openmote-cc2538/board.c
  arch/platform/openmote/openmote-cc2538/board.h
  arch/platform/openmote/openmote-cc2538/leds-arch.c
  arch/platform/openmote/platform.c
  examples/dev/button-hal/Makefile
  examples/dev/gpio-hal/Makefile
  examples/dev/gpio-hal/openmote/pins.c
  examples/mqtt-client/Makefile
  examples/mqtt-client/arch/platform/openmote/Makefile.openmote
  examples/mqtt-client/arch/platform/openmote/module-macros.h
  examples/mqtt-client/arch/platform/openmote/mqtt-client-extensions.c
  examples/platform-specific/cc2538-common/Makefile
  examples/platform-specific/cc2538-common/crypto/Makefile
  examples/platform-specific/cc2538-common/pka/Makefile
  examples/sensniff/Makefile
  examples/sensniff/openmote/target-conf.h
  examples/storage/cfs-coffee/README.md
  tests/03-compile-arm-ports-02/Makefile
  tests/19-out-of-tree-build/Makefile
Labels: pr/enhancement, pr/include-in-v4.4

#1078 TSCH: move all ctimer manipulations outside from the interrupt context
  os/net/mac/tsch/tsch-slot-operation.c
  os/net/mac/tsch/tsch.c
  os/net/mac/tsch/tsch.h
Labels: bug, pr/bugfix, pr/include-in-v4.4

#1048 fix the removal of extension header on fallback interface
  os/net/ipv6/tcpip.c
Labels: bug, pr/include-in-v4.4

#1077 Misc. RPL-Lite fixes
  os/net/routing/rpl-lite/rpl-dag.c
  os/net/routing/rpl-lite/rpl-neighbor.c
  os/net/routing/rpl-lite/rpl-types.h
Labels: pr/bugfix, pr/include-in-v4.4

#1053 add multiple channel option to Orchestra unicast slotframe
  os/net/mac/tsch/tsch-queue.c
  os/net/mac/tsch/tsch-schedule.c
  os/net/mac/tsch/tsch-slot-operation.c
  os/net/mac/tsch/tsch-slot-operation.h
  os/net/packetbuf.h
  os/services/orchestra/orchestra-conf.h
  os/services/orchestra/orchestra-rule-default-common.c
  os/services/orchestra/orchestra-rule-eb-per-time-source.c
  os/services/orchestra/orchestra-rule-unicast-per-neighbor-rpl-ns.c
  os/services/orchestra/orchestra-rule-unicast-per-neighbor-rpl-storing.c
  os/services/orchestra/orchestra.c
  os/services/orchestra/orchestra.h
Labels: pr/include-in-v4.4

#1107 Fix and test TSCH-enabled border router for platform Zoul
  os/services/rpl-border-router/Makefile.rpl-border-router
  os/services/rpl-border-router/zoul/module-macros.h
  tests/03-compile-arm-ports-02/Makefile
Labels: bug/low, pr/bugfix, pr/include-in-v4.4

#1109 Add README link to nightly builds
  README.md
Labels: pr/include-in-v4.4

#1111 Nightly testbed tests: add new config for multiple choffset Orchestra
  examples/benchmarks/rpl-req-resp/Makefile
  examples/benchmarks/rpl-req-resp/project-conf.h
Labels: pr/include-in-v4.4

#1108 Add support for multiple docker containers
  .travis.yml
Labels: pr/enhancement
