Repository contiki-ng/contiki-ng, pull requests merged in 2019-05, with the labels that each got.

#919 Implemented MPL
  examples/multicast/project-conf.h
  examples/multicast/root.c
  examples/multicast/sink.c
  os/net/ipv6/multicast/mpl.c
  os/net/ipv6/multicast/mpl.h
  os/net/ipv6/multicast/uip-mcast6-engines.h
  os/net/ipv6/multicast/uip-mcast6.h
  os/net/ipv6/uip-icmp6.h
  os/net/ipv6/uip.h
  os/net/ipv6/uip6.c
  tests/07-simulation-base/14-cooja-multicast-11-hops-mpl.csc
Labels: pr/enhancement, pr/include-in-v4.3

#908 Maximal packet size unification
  arch/cpu/cc2538/cc2538-conf.h
  arch/cpu/cc2538/dev/cc2538-rf.c
  arch/cpu/cc26x0-cc13x0/cc13xx-cc26xx-conf.h
  arch/cpu/cc26x0-cc13x0/rf-core/ieee-mode.c
  arch/cpu/cc26x0-cc13x0/rf-core/prop-mode.c
  arch/cpu/msp430/msp430-conf.h
  arch/cpu/simplelink-cc13xx-cc26xx/cc13xx-cc26xx-conf.h
  arch/cpu/simplelink-cc13xx-cc26xx/rf/ieee-mode.c
  arch/cpu/simplelink-cc13xx-cc26xx/rf/prop-mode.c
  arch/dev/cc1200/cc1200-conf.h
  arch/dev/cc2420/cc2420.c
  arch/platform/cooja/contiki-conf.h
  arch/platform/cooja/dev/cooja-radio.c
  arch/platform/jn516x/contiki-conf.h
  arch/platform/jn516x/dev/micromac-radio.c
  arch/platform/native/contiki-conf.h
  arch/platform/nrf52dk/contiki-conf.h
  examples/platform-specific/cc26x0-cc13x0/ble-ipv6/README.md
  examples/platform-specific/cc26x0-cc13x0/ble-ipv6/project-conf.h
  os/contiki-default-conf.h
  os/net/mac/csma/csma.h
  os/net/mac/tsch/tsch-const.h
  os/net/netstack.h
  tools/viewconf/viewconf.c
Labels: pr/bugfix, pr/include-in-v4.3

#694 Extend the GPIO HAL to support a port/pin numbering scheme
  arch/cpu/cc2538/cc2538-def.h
  arch/cpu/cc2538/dev/gpio-hal-arch.c
  arch/cpu/cc2538/dev/gpio-hal-arch.h
  arch/cpu/cc26x0-cc13x0/cc13xx-cc26xx-def.h
  arch/cpu/cc26x0-cc13x0/dev/gpio-hal-arch.c
  arch/cpu/cc26x0-cc13x0/dev/gpio-hal-arch.h
  arch/cpu/native/dev/gpio-hal-arch.c
  arch/cpu/native/native-def.h
  arch/cpu/simplelink-cc13xx-cc26xx/cc13xx-cc26xx-conf.h
  arch/cpu/simplelink-cc13xx-cc26xx/cc13xx-cc26xx-def.h
  arch/cpu/simplelink-cc13xx-cc26xx/dev/gpio-hal-arch.c
  arch/cpu/simplelink-cc13xx-cc26xx/dev/gpio-hal-arch.h
  arch/dev/ext-flash/ext-flash.c
  arch/platform/simplelink/cc13xx-cc26xx/srf06/als-sensor.c
  examples/dev/gpio-hal/README.md
  examples/dev/gpio-hal/gpio-hal-example.c
  os/dev/button-hal.c
  os/dev/button-hal.h
  os/dev/gpio-hal.c
  os/dev/gpio-hal.h
  os/dev/leds.c
  os/dev/leds.h
  os/dev/spi.c
  os/dev/spi.h
Labels: pr/enhancement, pr/include-in-v4.3

#902 Fix zoul battery voltage conversion and add example
  arch/platform/zoul/remote-revb/power-mgmt.c
  arch/platform/zoul/remote-revb/power-mgmt.h
  examples/platform-specific/zoul/Makefile
  examples/platform-specific/zoul/test-vbat.c
Labels: bug, bug/low, pr/bugfix, pr/include-in-v4.3

#943 SimpleLink tickless mode
  arch/cpu/simplelink-cc13xx-cc26xx/cc13xx-cc26xx-conf.h
  arch/cpu/simplelink-cc13xx-cc26xx/dev/clock-arch.c
  arch/cpu/simplelink-cc13xx-cc26xx/dev/clock-arch.h
  arch/cpu/simplelink-cc13xx-cc26xx/dev/watchdog-arch.c
  arch/cpu/simplelink-cc13xx-cc26xx/dev/watchdog-arch.h
  arch/platform/simplelink/cc13xx-cc26xx/platform.c
Labels: pr/enhancement

#948 Fixed erroneous pointer cast in IEEE CCA request function
  arch/cpu/simplelink-cc13xx-cc26xx/rf/ieee-mode.c
Labels: pr/bugfix, pr/include-in-v4.3

#950 Explicitly document libraries that are unsafe to use within interrupts
  os/dev/watchdog.h
  os/lib/circular-list.h
  os/lib/dbl-circ-list.h
  os/lib/dbl-list.h
  os/lib/list.h
  os/lib/queue.h
  os/lib/stack.h
  os/lib/trickle-timer.h
  os/sys/ctimer.h
  os/sys/etimer.h
Labels: documentation, pr/include-in-v4.3

#960 Provide non-returning assert() implementation
  arch/platform/cooja/contiki-conf.h
  os/lib/assert.c
  os/lib/assert.h
  os/sys/cc-gcc.h
  os/sys/cc.h
Labels: pr/bugfix

#964 Update Readme.md
  README.md
Labels: pr/include-in-v4.3

#946 Remove watchdog_periodic() calls that may happen inside an interrupt context
  arch/cpu/cc2538/usb/usb-arch.c
  arch/cpu/cc26x0-cc13x0/rf-core/prop-mode.c
  arch/cpu/nrf52832/ble/ble-mac.c
Labels: pr/bugfix, pr/include-in-v4.3

#963 TSCH: fix the reselection of the current_link in case it becomes NULL during a packet burst
  os/net/mac/tsch/tsch-slot-operation.c
Labels: pr/include-in-v4.3

#915 Improve MODULE dependency handling
  Makefile.include
  os/services/shell/Makefile.shell
  os/services/shell/module-macros.h
Labels: bug, bug/medium, pr/bugfix, pr/include-in-v4.3

#947 Fix the jn516x build system when SDK_BASE_DIR is misconfigured
  arch/platform/jn516x/Makefile.jn516x
Labels: pr/bugfix
