Repository contiki-ng/contiki-ng, pull requests merged in 2019-04, with the labels that each got.

#865 Fix build system for individual object files
  Makefile.include
Labels: pr/bugfix

#867 Enhanced safety in the IPv6 extension header processing
  os/net/ipv6/uip-icmp6.c
  os/net/ipv6/uip.h
  os/net/ipv6/uip6.c
  os/net/ipv6/uipbuf.c
  os/net/routing/nullrouting/nullrouting.c
  os/net/routing/routing.h
  os/net/routing/rpl-classic/rpl-ext-header.c
  os/net/routing/rpl-classic/rpl.h
  os/net/routing/rpl-lite/rpl-ext-header.c
  os/net/routing/rpl-lite/rpl-ext-header.h
Labels: bug/vulnerability, pr/bugfix

#871 Verify that uip_len is acceptable before continuing with packet processing.
  os/net/ipv6/uip6.c
Labels: bug/vulnerability, pr/bugfix

#904 Fix RPL Lite compilation when probing is disabled
  os/net/routing/rpl-lite/rpl-neighbor.c
  os/net/routing/rpl-lite/rpl.c
Labels: pr/bugfix, pr/include-in-v4.3

#917 Multicast Tests Fix
  tests/07-simulation-base/15-cooja-multicast-11-hops-rollt-tm.csc
  tests/07-simulation-base/16-cooja-multicast-11-hops-smrf.csc
  tests/07-simulation-base/17-cooja-multicast-11-hops-esmrf.csc
  tests/07-simulation-base/18-cooja-multicast-31-hops.csc
Labels: pr/bugfix, pr/include-in-v4.3

#921 sixtop: add missing methods of test_mac_driver (tests/13-ieee802154)
  tests/13-ieee802154/code-6tisch/common.c
Labels: pr/bugfix

#923 Fix sensniff and explicitly disable all upper layer networking
  examples/sensniff/Makefile
  examples/sensniff/sensniff-mac.c
Labels: bug, bug/low, pr/bugfix, pr/include-in-v4.3

#925 Allow default baud rate override
  arch/cpu/cc26x0-cc13x0/Makefile.cc26x0-cc13x0
  arch/platform/zoul/Makefile.zoul
  examples/sensniff/Makefile
Labels: bug, bug/low, pr/bugfix, pr/include-in-v4.3

#914 Don't specify arch/platform/zoul as a directory twice
  arch/platform/zoul/Makefile.zoul
Labels: bug, bug/low, pr/bugfix, pr/include-in-v4.3

#913 Don't pass -I<platform-dir> twice
  Makefile.include
Labels: bug, bug/low, pr/bugfix, pr/include-in-v4.3

#929 Fix RPL acceptable rank check
  os/net/routing/rpl-classic/rpl-dag.c
  os/net/routing/rpl-lite/rpl-neighbor.c
Labels: pr/include-in-v4.3

#912 Tidy-up doxygen module hierarchy
  arch/platform/cc26x0-cc13x0/launchpad/board-buttons.c
  os/net/mac/csma/csma.h
  os/net/routing/nullrouting/nullrouting.c
  os/net/routing/routing.h
  os/net/routing/rpl-lite/rpl.h
  os/services/deployment/deployment.h
  os/services/lwm2m/lwm2m-queue-mode-object.h
  os/services/lwm2m/lwm2m-queue-mode.h
  os/services/shell/shell-commands.h
  os/services/shell/shell.c
  os/services/shell/shell.h
  os/services/simple-energest/simple-energest.h
  os/sys/node-id.h
Labels: documentation, pr/include-in-v4.3

#922 Fix CC13x0 prop mode under CSMA
  arch/cpu/cc26x0-cc13x0/rf-core/prop-mode.c
Labels: bug, bug/critical, pr/bugfix, pr/include-in-v4.3
