Repository contiki-ng/contiki-ng, pull requests merged in 2020-10, with the labels that each got.

#1410 Prevent infinite loop in ND6
  os/net/ipv6/uip-nd6.c
  tests/20-packet-parsing/packet-injector/sicslowpan-data/sicslowpan-packet-70
Labels: bug/vulnerability

#1409 Prevent out-of-bounds write when processing external headers in sicslowpan
  os/net/ipv6/sicslowpan.c
  tests/20-packet-parsing/packet-injector/sicslowpan-data/sicslowpan-packet-69
Labels: bug/vulnerability

#1355 Bugfix/snmp engine
  os/net/app-layer/snmp/snmp-ber.c
  os/net/app-layer/snmp/snmp-engine.c
  os/net/app-layer/snmp/snmp-message.c
Labels: bug/vulnerability, pr/bugfix

#1413 SimpleLink and CC26x0-CC13x0 platforms: timining adjustments to make SCH more usable on SimpleLink
  arch/cpu/cc26x0-cc13x0/rf-core/cc13xx-50kbps-tsch.c
  arch/cpu/simplelink-cc13xx-cc26xx/cc13xx-cc26xx-def.h
  arch/cpu/simplelink-cc13xx-cc26xx/rf/cc13xx-50kbps-tsch.c
  arch/cpu/simplelink-cc13xx-cc26xx/rf/ieee-mode.c
Labels: pr/bugfix, pr/enhancement

#1415 Tidy up tunslip6 usage and help messages
  tools/serial-io/tunslip6.c
Labels: documentation

#1418 nrf52840: Use correct flash and RAM length in dk linker script
  arch/cpu/nrf52840/ld/nrf52840.ld
Labels: pr/bugfix

#1419 nrf52840: Fix build when using SEGGER RTT
  arch/platform/nrf52840/rtt/segger-rtt-conf.h
  arch/platform/nrf52840/rtt/segger-rtt.h
Labels: pr/bugfix

#1243 Re-organise the arch/dev directory
  Makefile.dir-variables
  arch/dev/etc/ds2411/ds2411.c
  arch/dev/etc/ds2411/ds2411.h
  arch/dev/etc/rgb-led/rgb-led.c
  arch/dev/etc/rgb-led/rgb-led.h
  arch/dev/ethernet/enc28j60/enc28j60-ip64-driver.c
  arch/dev/ethernet/enc28j60/enc28j60-ip64-driver.h
  arch/dev/ethernet/enc28j60/enc28j60.c
  arch/dev/ethernet/enc28j60/enc28j60.h
  arch/dev/radio/cc1200/cc1200-802154g-863-870-fsk-50kbps.c
  arch/dev/radio/cc1200/cc1200-868-4gfsk-1000kbps.c
  arch/dev/radio/cc1200/cc1200-868-fsk-1-2kbps.c
  arch/dev/radio/cc1200/cc1200-arch.h
  arch/dev/radio/cc1200/cc1200-conf.h
  arch/dev/radio/cc1200/cc1200-const.h
  arch/dev/radio/cc1200/cc1200-rf-cfg.h
  arch/dev/radio/cc1200/cc1200.c
  arch/dev/radio/cc2420/cc2420-tsch-15ms.c
  arch/dev/radio/cc2420/cc2420-tsch-15ms.h
  arch/dev/radio/cc2420/cc2420.c
  arch/dev/radio/cc2420/cc2420.h
  arch/dev/radio/cc2420/cc2420_const.h
  arch/dev/sensor/bme280/README.bme280
  arch/dev/sensor/bme280/bme280-arch.h
  arch/dev/sensor/bme280/bme280-sensor.c
  arch/dev/sensor/bme280/bme280-sensor.h
  arch/dev/sensor/bme280/bme280.c
  arch/dev/sensor/bme280/bme280.h
  arch/dev/sensor/sht11/sht11-sensor.c
  arch/dev/sensor/sht11/sht11-sensor.h
  arch/dev/sensor/sht11/sht11.c
  arch/dev/sensor/sht11/sht11.h
  arch/dev/storage/disk/disk.h
  arch/dev/storage/disk/mmc/mmc-arch.h
  arch/dev/storage/disk/mmc/mmc.c
  arch/dev/storage/disk/mmc/mmc.h
  arch/dev/storage/ext-flash/README.md
  arch/dev/storage/ext-flash/ext-flash.c
  arch/dev/storage/ext-flash/ext-flash.h
  arch/platform/cc26x0-cc13x0/launchpad/Makefile.launchpad
  arch/platform/cc26x0-cc13x0/sensortag/Makefile.sensortag
  arch/platform/nrf52840/dongle/Makefile.dongle
  arch/platform/sky/Makefile.sky
  arch/platform/sky/contiki-conf.h
  arch/platform/sky/platform.c
  arch/platform/z1/Makefile.z1
  arch/platform/z1/contiki-conf.h
  arch/platform/z1/platform.c
  arch/platform/zoul/Makefile.zoul
  arch/platform/zoul/dev/mmc-arch.c
  arch/platform/zoul/fs/fat/diskio.c
  arch/platform/zoul/orion/Makefile.orion
  arch/platform/zoul/remote-reva/Makefile.remote-reva
  arch/platform/zoul/remote-revb/Makefile.remote-revb
  examples/dev/rgb-led/rgb-led-example.c
  examples/platform-specific/zoul/Makefile
  examples/platform-specific/zoul/test-bme280.c
Labels: pr/enhancement

#1420 GH Actions: keep docker image with tag 'latest' up-to-date
  .github/workflows/build.yml
Labels: pr/enhancement

#1425 Only run docker push if we just built a new image
  .github/workflows/build.yml
Labels: pr/enhancement

#1287 Fix sensortag reed relay logic
  arch/platform/cc26x0-cc13x0/sensortag/board-buttons.c
  arch/platform/simplelink/cc13xx-cc26xx/sensortag/button-sensor-arch.c
Labels: pr/bugfix
