Repository contiki-ng/contiki-ng, pull requests merged in 2020-11, with the labels that each got.

#1276 Add optional support for X in our Vagrant image
  tools/vagrant/bootstrap-vbox-with-x.sh
Labels: pr/enhancement

#1395 Add a result visualization example with logfile analysis and plotting script
  examples/benchmarks/result-visualization/Makefile
  examples/benchmarks/result-visualization/README.md
  examples/benchmarks/result-visualization/cooja.csc
  examples/benchmarks/result-visualization/coojalogger.js
  examples/benchmarks/result-visualization/node.c
  examples/benchmarks/result-visualization/project-conf.h
  examples/benchmarks/result-visualization/run-analysis.py
  examples/benchmarks/result-visualization/run-cooja.py
  tests/06-script-base/04-test-result-visualization.sh
  tests/06-script-base/code-result-visualization/00-result-visualization.csc
  tests/06-script-base/code-result-visualization/00-result-visualization.js
  tests/06-script-base/code-result-visualization/Makefile
  tests/Makefile.simulation-test
  tools/docker/Dockerfile
Labels: pr/enhancement

#1422 Extend documentation of the radio API
  os/dev/radio.h
Labels: documentation

#1431 Validate the address pointer in the source routing header
  os/net/routing/rpl-classic/rpl-ext-header.c
  os/net/routing/rpl-lite/rpl-ext-header.c
  tests/20-packet-parsing/packet-injector/sicslowpan-data/sicslowpan-packet-71
Labels: bug/vulnerability

#1421 Tidy-up CC2538 SHR search handling
  arch/cpu/cc2538/dev/cc2538-rf.c
Labels: pr/enhancement

#1437 fix number of strncpy uses in the native platform
  arch/cpu/native/net/tun6-net.c
  arch/platform/native/cfs-posix-dir.c
Labels: pr/bugfix

#1313 Fixed coap packet parser message buffer out-of-bounds read bugs.
  os/net/app-layer/coap/coap.c
Labels: pr/bugfix

#1442 Update Github Actions: replace set-env with environment files
  .github/workflows/build.yml
Labels: bug/critical, pr/bugfix

#1290 Make the CC13xx/CC26xx base demo work for platform simplelink too
  examples/platform-specific/cc26x0-cc13x0/Makefile
  examples/platform-specific/cc26x0-cc13x0/base-demo/Makefile
  examples/platform-specific/cc26x0-cc13x0/base-demo/Makefile.target
  examples/platform-specific/cc26x0-cc13x0/base-demo/README.md
  examples/platform-specific/cc26x0-cc13x0/base-demo/base-demo.c
  examples/platform-specific/cc26x0-cc13x0/base-demo/cc26x0-cc13x0/target-conf.h
  examples/platform-specific/cc26x0-cc13x0/base-demo/project-conf.h
  examples/platform-specific/cc26x0-cc13x0/base-demo/simplelink/target-conf.h
  tests/02-compile-arm-ports/Makefile
Labels: pr/enhancement

#1283 Various fixes for Simplelink/sensortag sensors
  arch/platform/simplelink/cc13xx-cc26xx/Makefile.cc13xx-cc26xx
  arch/platform/simplelink/cc13xx-cc26xx/sensortag/bmp-280-sensor.c
  arch/platform/simplelink/cc13xx-cc26xx/sensortag/hdc-1000-sensor.c
  arch/platform/simplelink/cc13xx-cc26xx/sensortag/opt-3001-sensor.c
  arch/platform/simplelink/cc13xx-cc26xx/sensortag/tmp-007-sensor.c
Labels: bug, bug/medium, pr/bugfix

#1285 Add I2C manipulation module for platform Simplelink
  arch/cpu/simplelink-cc13xx-cc26xx/Makefile.cc13xx-cc26xx
  arch/cpu/simplelink-cc13xx-cc26xx/dev/i2c-arch.c
  arch/cpu/simplelink-cc13xx-cc26xx/dev/i2c-arch.h
  arch/platform/simplelink/cc13xx-cc26xx/sensortag/bmp-280-sensor.c
  arch/platform/simplelink/cc13xx-cc26xx/sensortag/hdc-1000-sensor.c
  arch/platform/simplelink/cc13xx-cc26xx/sensortag/mpu-9250-sensor.c
  arch/platform/simplelink/cc13xx-cc26xx/sensortag/opt-3001-sensor.c
  arch/platform/simplelink/cc13xx-cc26xx/sensortag/tmp-007-sensor.c
Labels: pr/enhancement, pr/work-in-progress

#1451 Fix TMP007 and HDC1000 sensor readings on the Simplelink platform
  arch/platform/simplelink/cc13xx-cc26xx/sensortag/hdc-1000-sensor.c
  arch/platform/simplelink/cc13xx-cc26xx/sensortag/tmp-007-sensor.c
Labels: pr/bugfix

#1448 BSL: Change PYTHON value to python3
  arch/cpu/cc26x0-cc13x0/Makefile.cc26x0-cc13x0
  arch/cpu/simplelink-cc13xx-cc26xx/Makefile.cc13xx-cc26xx
  arch/platform/cc2538dk/Makefile.cc2538dk
  arch/platform/openmote/Makefile.openmote
  arch/platform/zoul/Makefile.zoul
Labels: pr/bugfix
