Repository contiki-ng/contiki-ng, pull requests merged in 2020-04, with the labels that each got.

#1197 MQTT: increase size of variable i to avoid potential infinite loop
  os/net/app-layer/mqtt/mqtt.c
Labels: bug/vulnerability, pr/bugfix

#1229 Add missing include
  os/net/ipv6/uip-ds6.h
Labels: pr/bugfix, pr/include-in-v4.5

#1230 Allow the MQTT client example for platform Cooja
  examples/mqtt-client/Makefile
Labels: pr/include-in-v4.5

#1173 Fix out-of-bounds uIP data pointer on some TCP URG segments
  os/net/ipv6/uip6.c
Labels: bug/vulnerability, pr/include-in-v4.5

#1236 build all script: account for skipped examples
  tests/compile-all/build.sh
Labels: pr/include-in-v4.5

#1244 Make sure we are testing all board code
  tests/02-compile-arm-ports/Makefile
Labels: pr/enhancement, pr/include-in-v4.5

#1245 Clean up .gitignore
  .gitignore
Labels: pr/include-in-v4.5

#987 Update 6P for better conformance with IETF RFC 8480
  examples/6tisch/6p-packet/test-sf.c
  examples/6tisch/etsi-plugtest-2017/sf-plugtest.c
  examples/6tisch/sixtop/sf-simple.c
  os/net/mac/tsch/sixtop/sixp-pkt.c
  os/net/mac/tsch/sixtop/sixp-pkt.h
  os/net/mac/tsch/sixtop/sixp-trans.c
  os/net/mac/tsch/sixtop/sixp-trans.h
  os/net/mac/tsch/sixtop/sixp.c
  os/net/mac/tsch/sixtop/sixp.h
  os/net/mac/tsch/sixtop/sixtop.c
  os/net/mac/tsch/sixtop/sixtop.h
  tests/13-ieee802154/08-cooja-test-sixtop-sf-error-handler.csc
  tests/13-ieee802154/code-6tisch/common.c
  tests/13-ieee802154/code-6tisch/common.h
  tests/13-ieee802154/code-6tisch/test-sixp-trans.c
  tests/13-ieee802154/code-6tisch/test-sixp.c
  tests/13-ieee802154/code-6tisch/test-sixtop-sf-error-handler.c
  tests/13-ieee802154/code-6tisch/test-sixtop.c
Labels: pr/enhancement, pr/include-in-v4.5

#1248 MQTT: Provide the message id for subscribe, unsubscribe and publish
  os/net/app-layer/mqtt/mqtt.c
Labels: pr/enhancement

#1222 Cooja mote improvements
  arch/platform/cooja/dev/cooja-radio.c
Labels: pr/include-in-v4.5

#1240 TSCH: fix channel_offset in the logs if taken from a packet, and refactor TSCH channel / channel_offset selection inside a slot
  os/net/mac/tsch/tsch-log.c
  os/net/mac/tsch/tsch-log.h
  os/net/mac/tsch/tsch-slot-operation.c
  os/net/mac/tsch/tsch-slot-operation.h
  os/net/mac/tsch/tsch.h
Labels: pr/include-in-v4.5
