Repository contiki-ng/contiki-ng, pull requests merged in 2020-09, with the labels that each got.

#1366 Verify the TCP data offset to avoid uip_len overflows.
  os/net/ipv6/uip6.c
Labels: bug/vulnerability

#1380 Add missing lib/sensors.h includes
  arch/platform/cc2538dk/dev/smartrf-sensors.c
  arch/platform/cc26x0-cc13x0/sensortag/bmp-280-sensor.h
  arch/platform/cc26x0-cc13x0/sensortag/mpu-9250-sensor.h
  arch/platform/cc26x0-cc13x0/sensortag/opt-3001-sensor.h
  arch/platform/cc26x0-cc13x0/sensortag/sensortag-sensors.c
  arch/platform/cc26x0-cc13x0/sensortag/tmp-007-sensor.h
  arch/platform/cc26x0-cc13x0/srf06/srf06-sensors.c
  arch/platform/simplelink/cc13xx-cc26xx/batmon-sensor.h
  arch/platform/simplelink/cc13xx-cc26xx/sensortag/mpu-9250-sensor.h
  arch/platform/simplelink/cc13xx-cc26xx/sensortag/opt-3001-sensor.h
  arch/platform/simplelink/cc13xx-cc26xx/sensortag/tmp-007-sensor.h
Labels: pr/bugfix

#1385 Make sure sensors-process runs when needed in simplelink platform
  arch/platform/simplelink/cc13xx-cc26xx/platform.c
Labels: pr/bugfix

#1307 TSCH: also update backoff for Tx links that are overlapped by Rx links
  os/net/mac/tsch/tsch-slot-operation.c
Labels: pr/bugfix

#1286 Delete the obsolete very-sleepy-demo
  examples/platform-specific/cc26x0-cc13x0/very-sleepy-demo/Makefile
  examples/platform-specific/cc26x0-cc13x0/very-sleepy-demo/Makefile.target
  examples/platform-specific/cc26x0-cc13x0/very-sleepy-demo/README.md
  examples/platform-specific/cc26x0-cc13x0/very-sleepy-demo/project-conf.h
  examples/platform-specific/cc26x0-cc13x0/very-sleepy-demo/very-sleepy-demo.c
  tests/02-compile-arm-ports/Makefile
Labels: pr/bugfix

#1392 TSCH: Enable hardware timestamps on nRF52840
  arch/cpu/nrf52840/nrf52840-def.h
Labels: pr/bugfix, pr/enhancement

#1391 Include LWM2M protocol version in registration message
  os/services/lwm2m/lwm2m-rd-client.c
  os/services/lwm2m/lwm2m-rd-client.h
Labels: pr/bugfix

#1316 Add GPIO HAL support for the nRF52840 cpu and targets
  arch/cpu/nrf52840/Makefile.nrf52840
  arch/cpu/nrf52840/dev/gpio-hal-arch.c
  arch/cpu/nrf52840/dev/gpio-hal-arch.h
  arch/cpu/nrf52840/nrf52840-def.h
  arch/platform/nrf52840/dk/Makefile.dk
  arch/platform/nrf52840/dk/board-buttons.c
  arch/platform/nrf52840/dk/board-leds.c
  arch/platform/nrf52840/dk/button-sensor.c
  arch/platform/nrf52840/dk/button-sensor.h
  arch/platform/nrf52840/dk/leds-arch.c
  arch/platform/nrf52840/dk/nrf52840-board-def.h
  arch/platform/nrf52840/dk/nrf52840dk-sensors.c
  arch/platform/nrf52840/dongle/Makefile.dongle
  arch/platform/nrf52840/dongle/board-buttons.c
  arch/platform/nrf52840/dongle/board-leds.c
  arch/platform/nrf52840/dongle/button-sensor.c
  arch/platform/nrf52840/dongle/button-sensor.h
  arch/platform/nrf52840/dongle/leds-arch.c
  arch/platform/nrf52840/dongle/nrf52840-board-def.h
  arch/platform/nrf52840/dongle/nrf52840dongle-sensors.c
  arch/platform/nrf52840/platform.c
  examples/dev/gpio-hal/Makefile
  examples/dev/gpio-hal/README.md
  examples/dev/gpio-hal/gpio-hal-example.c
  examples/dev/gpio-hal/nrf52840/pins.c
  examples/dev/rgb-led/Makefile
Labels: pr/enhancement

#1318 Allow the button HAL to deal with buttons connected on different ports
  os/dev/button-hal.c
  os/dev/button-hal.h
Labels: pr/bugfix
