Repository contiki-ng/contiki-ng, pull requests merged in 2021-05, with the labels that each got.

#1541 Fix out-of-bounds read in SNMP
  os/net/app-layer/snmp/snmp-engine.c
Labels: bug/vulnerability

#1517 Fix the length field check for SNMP input packets
  os/net/app-layer/snmp/snmp-ber.c
Labels: bug/vulnerability

#1463 Fix overflow bug in the HeapMem module
  os/lib/heapmem.c
Labels: bug/medium, bug/vulnerability

#1580 Fixed variable declaration on headers on ARM GCC 10
  arch/cpu/cc2538/dev/ecc-curve.h
  arch/dev/sensor/bme280/bme280.c
  arch/dev/sensor/bme280/bme280.h
Labels: pr/bugfix

#1577 DHT11 Sensor
  arch/dev/sensor/dht11/dht11-sensor.c
  arch/dev/sensor/dht11/dht11-sensor.h
  examples/dev/dht11/Makefile
  examples/dev/dht11/dht11.c
  tests/02-compile-arm-ports/Makefile
Labels: pr/enhancement

#1561 CC1200: 802.15.4g mode fixes/improvements, and compile test added
  arch/dev/radio/cc1200/cc1200-conf.h
  arch/dev/radio/cc1200/cc1200.c
  tests/02-compile-arm-ports/Makefile
Labels: pr/bugfix
