Repository contiki-ng/contiki-ng, pull requests merged in 2021-03, with the labels that each got.

#1524 Add nRF52840 support to sensniff
  arch/cpu/nrf52840/clock.c
  arch/cpu/nrf52840/dbg.c
  arch/cpu/nrf52840/dev/uart0.c
  arch/cpu/nrf52840/dev/watchdog.c
  arch/cpu/nrf52840/nrf52840-conf.h
  arch/cpu/nrf52840/rf/nrf52840-ieee.c
  arch/platform/nrf52840/common/temperature-sensor.c
  examples/sensniff/Makefile
  examples/sensniff/README.md
  examples/sensniff/nrf52840/target-conf.h
  examples/sensniff/pool/nrf52840-io.h
Labels: pr/enhancement

#1506 Add buffer boundary check in sicslowpan
  os/net/ipv6/sicslowpan.c
Labels: bug/vulnerability

#1529 Move doxygen modules to the correct location
  arch/cpu/nrf52840/usb/usb-dfu-trigger.c
  arch/cpu/nrf52840/usb/usb-dfu-trigger.h
  arch/cpu/simplelink-cc13xx-cc26xx/rf/rat.c
Labels: documentation

#1530 Change what text files we consider for the doxygen build
  arch/platform/sky/doxygen-group.txt
  os/sys/pt.h
  tools/doxygen/Makefile
  tools/doxygen/doxygen-mainpage.txt
  tools/doxygen/doxygen-modules.txt
  tools/doxygen/pt-doc.txt
Labels: documentation
