Repository contiki-ng/contiki-ng, pull requests merged in 2021-02, with the labels that each got.

#1500 Fix native target builds on macos
  arch/cpu/native/net/tun6-net.c
Labels: pr/bugfix

#1501 nrf52840: Implement USB power events for hotplug support
  arch/cpu/nrf52840/usb/Makefile.usb
  arch/cpu/nrf52840/usb/usb-serial.c
  arch/platform/nrf52840/config/sdk_config.h
Labels: bug/low, pr/bugfix

#1477 Add readme badges for community engagement spaces
  README.md
Labels: documentation

#1505 nrf52840: Always build power driver
  arch/cpu/nrf52840/Makefile.nrf52840
  arch/cpu/nrf52840/usb/Makefile.usb
Labels: bug/critical, pr/bugfix

#1476 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation
